{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "registry-creds.name" . }}
    chart: {{ template "registry-creds.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "registry-creds.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "registry-creds.fullname" . }}
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "registry-creds.fullname" . }}
{{- end }}