{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "registry-creds.name" . }}
    chart: {{ template "registry-creds.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "registry-creds.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["namespaces","serviceaccounts"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
{{- end }}