apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "registry-creds.fullname" . }}
  namespace: kube-system
  labels:
    app.kubernetes.io/name: {{ include "registry-creds.name" . }}
    helm.sh/chart: {{ include "registry-creds.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    version: v{{ .Values.image.tag }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "registry-creds.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "registry-creds.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        version: v{{ .Values.image.tag }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              configMapKeyRef:
                name: registry-creds
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              configMapKeyRef:
                name: registry-creds
                key: AWS_SECRET_ACCESS_KEY
          - name: awsaccount
            valueFrom:
              configMapKeyRef:
                name: registry-creds
                key: aws-account
          - name: awsregion
            valueFrom:
              configMapKeyRef:
                name: registry-creds
                key: aws-region
          - name: aws_assume_role
            valueFrom:
              configMapKeyRef:
                name: registry-creds
                key: aws_assume_role
          - name: DOCKER_PRIVATE_REGISTRY_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: registry-creds
                key: DOCKER_PRIVATE_REGISTRY_PASSWORD
          - name: DOCKER_PRIVATE_REGISTRY_SERVER
            valueFrom:
              configMapKeyRef:
                name: registry-creds
                key: DOCKER_PRIVATE_REGISTRY_SERVER
          - name: DOCKER_PRIVATE_REGISTRY_USER
            valueFrom:
              configMapKeyRef:
                name: registry-creds
                key: DOCKER_PRIVATE_REGISTRY_USER
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "registry-creds.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
