apiVersion: v1
kind: Secret
metadata:
  name: registry-creds-gcr
  namespace: kube-system
  labels:
    app: registry-creds
    kubernetes.io/minikube-addons: registry-creds
    cloud: gcr
data:
  application_default_credentials.json: {{ .Values.google.json }}
  gcrurl: {{ .Values.google.gcrurl }}
type: Opaque
