{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "registry-creds.name" . }}
    chart: {{ template "registry-creds.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "registry-creds.fullname" . }}
  namespace: kube-system
{{- end }}
