# Default values for registry-creds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: upmcenterprises/registry-creds
  tag: 1.9
  pullPolicy: IfNotPresent

private:
  server:   "changeme"
  user:     "changeme"
  password: "changeme"

aws:
  access_key: "changeme"
  secret_key: "changeme"
  account:    "changeme"
  region:     "changeme"
  role:       ""
  token:      ""

google:
  json:   "Y2hhbmdlbWU="
  gcrurl: "aHR0cHM6Ly9nY3IuaW8="
rbac:
  create: true

nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
